### PR TITLE
fix error messages `Undefined index`

### LINKED ISSUE #37: A bunch of error messages in log [NC13]
```

Error | PHP | Undefined index: HTTP_USER_AGENT at /var/www/nextcloud/apps/issuetemplate/lib/Sections/ClientSection.php#65 | 2017-12-19T18:45:12+0100
-- | -- | -- | --
Error | PHP | Undefined index: SERVER_SOFTWARE at /var/www/nextcloud/apps/issuetemplate/lib/Sections/ServerSection.php#86 | 2017-12-19T18:45:12+0100
Error | no app in context | issuetemplate | 2017-12-19T18:45:12+0100
Error | PHP | Undefined index: HTTP_USER_AGENT at /var/www/nextcloud/apps/issuetemplate/lib/Sections/ClientSection.php#65 | 2017-12-19T18:15:11+0100
Error | PHP | Undefined index: SERVER_SOFTWARE at /var/www/nextcloud/apps/issuetemplate/lib/Sections/ServerSection.php#86 | 2017-12-19T18:15:11+0100
Error | no app in context | issuetemplate | 2017-12-19T18:15:11+0100
Error | PHP | Method OC\L10N\L10NString::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#88 | 2017-12-19T18:10:47+0100
Error | PHP | vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/L10N/L10NString.php#79 | 2017-12-19T18:10:47+0100
Fatal | webdav | Sabre\DAV\Exception\Conflict: Parent node does not exist | 2017-12-19T18:00:52+0100
Fatal | webdav | Sabre\DAV\Exception\Conflict: Parent node does not exist | 2017-12-19T18:00:17+0100
Fatal | webdav | Sabre\DAV\Exception\Conflict: Parent node does not exist | 2017-12-19T17:59:48+0100
Fatal | webdav | Sabre\DAV\Exception\Conflict: Parent node does not exist | 2017-12-19T17:59:40+0100
Fatal | webdav | Sabre\DAV\Exception\Conflict: Parent node does not exist | 2017-12-19T17:57:14+0100
Fatal | webdav | Sabre\DAV\Exception\Conflict: Parent node does not exist | 2017-12-19T17:56:52+0100
```

### PR DESCRIPTION
**Pull request by tessus**
fix error messages in log:

```
Undefined index: HTTP_USER_AGENT at /data/projects/nextcloud/apps/issuetemplate/lib/Sections/ClientSection.php#65
Undefined index: SERVER_SOFTWARE at /data/projects/nextcloud/apps/issuetemplate/lib/Sections/ServerSection.php#86
```

thus fixes #37

### CODE REVIEW

**Comment by juliushaertl** [comment]
@tessus Thanks for your pull request. Looks good from the code side. Can you please sign your changes according to: https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by tessus** [comment]
@juliushaertl sure, I can do that. since I used gpg signing I didn't think this was still necessary.

It will take a bit time though, because I'm not quite sure how I can do that after the fact. a `git rebase -i` is not compatible with `--signoff`. I'll have to do some research.

**Comment by juliushaertl** [comment]
The easiest way is to do a `git rebase -i HEAD~2`, switch the `pick` to edit and run the following two commands for each commit:
```
git commit --amend --signoff
git rebase --continue
```

The gpg sign is to verify that you are the real author of the commit, while with adding a signoff message, you basically acknowledge that the commit is under the same license as the project.

**Comment by tessus** [comment]
done.

**Comment by juliushaertl** [comment]
Thanks for your contribution @tessus :+1:

**Pull request merged**
