### PR TITLE
Improved markdown styling and readability

### PR DESCRIPTION
**Pull request by contribguy**
Changes made:
- Better listing of loaded PHP-modules.
- Divided Enabled and Disabled apps into individual `<details>` blocks.
- Easier to read rendered code due to better usage of whitespace.
- Fixed various broken styling.

### CODE REVIEW

**Comment by juliushaertl** [comment]
@contribguy Thanks for your pull request. :+1: Looks really good, but I'd prefer to keep the single line display mode for attributes like os version, php version, ... otherwise a lot of scrolling is required when viewing the issue. Also the nbsp whitespaces make it a bit hard to view when it is not rendered.

**Comment by contribguy** [comment]
Hi @juliushaertl! Appreciate your comment on this.

When I made the changes I met two primary concerns. Readability and usability, ie. how easy the form is to fill out?

I didn't find any better way to accomplish whitespace after `<details>` end tag but to make the next element a header, in this case H4. This in turn made the answer, like os version, php version etc. pop down a bit, why I thought an indent was needed for readability. Do you have any ideas on how to do this?

I agree the `&nbsp;`-way to make an indent like this isn't pretty and makes it a bit hard for the end user to find where to fill in the detailed information. Are there any prettier way to accomplish this whitespace that you or anyone else know of?

It is as important that the issue created from this plugin is easy to read as it is to fill out. You should not have to be a developer or have coding skills to report something to the developers. This is why I think both readability and ease of reporting from the end user side are both very important. A key to get issues reported is to make it easy.

Regards

**Comment by juliushaertl** [comment]
@contribguy Thanks for adjusting. :+1: Looks good to me.

**Comment by contribguy** [comment]
Closing #25 ?

**Pull request merged**
